# SITE CONFIGURATION
title: UTM Robotics # your site title
author: UTM Robotics Team # You :P
description: > # Meta description of Homepage
  Website for the UTM Robotics Club.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://utmrobotics.com" # the base hostname & protocol for your site, e.g. http://example.com
future: true

gcalendar_api_key: 'AIzaSyBdneAWrblAZs7Vln1VfKoKQhG1kd3WbSg'

# SEO PLUGIN
# social:
#  name: Your Name
#  links:
#    - https://twitter.com/BenBalter
#    - https://www.facebook.com/ben.balter
#    - https://www.linkedin.com/in/BenBalter
#    - https://plus.google.com/+BenBalter
#    - https://github.com/benbalter
#    - https://keybase.io/benbalter

# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Calendar', link: '/calendar'}
  - {name: 'Projects', link: '/projects'}
  - {name: 'About', link: '/about'}

#tagline: >
#  Modern Jekyll theme focused on speed performance &amp; SEO best practices

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

# email: your-email@domain.com # email for form submission

twitter_username: utmrobotics # replace with your_twitter_username or comment to remove link from footer
facebook_username: utmrobotics
# github_username:  bla # replace with your_github_username or comment to remove link from footer
instagram_username: utm_robotics # replace with your_instagram_username or comment to remove link from footer
slack_link: https://utmrobotics.slack.com/join/shared_invite/enQtODM5MDg4NTk2MDgzLTUxOWE4MmY4MmRiYzQ2ZWI4ZjI1Y2Q1NDQyNzYwYTk1ZmFiMjM4MTVmZThiNWQwMjc5MDc5YWFkY2I1ZmU4YTA

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
# theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg
  - old_site

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
